[package]
name = "pbrt"
version = "0.1.0"
authors = ["Laurent Laborde <kerdezixe@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3

[dependencies]
rayon = "1.5.0"
chrono = "0.4.19"
ultraviolet = "0.8.0"
rand = "0.8.3"
image = "0.23.14"
